{% set name = "django-model-utils" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-model-utils-{{ version }}.tar.gz
  sha256: 08715a87fe114d1038c889c1c9eadade5f400f16230a9988e6ee36ace589240b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - model_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-model-utils
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Django model mixins and utilities.
  description: Django model mixins and utilities. django-model-utils supports Django 1.8 through 1.10 (latest bugfix release in each series only) on Python 2.7, 3.3 (Django 1.8 only), 3.4 and 3.5.
  doc_url: https://django-model-utils.readthedocs.io/en/latest/
  dev_url: https://github.com/jazzband/django-model-utils

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
    - rxm7706
    - millsks
    - elanqo
    - zaigner
